/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import vistas.Inventario;

/**
 *
 * @author Emili
 */
public class Gestion_datos extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_datos
     */
    public Gestion_datos() {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(this);
    }
    
    Inventario inv = new Inventario ();
    VistaClientes vc = new VistaClientes();
    vista_categorias vsc = new vista_categorias();
    Proveedor pr = new Proveedor();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btcliente = new javax.swing.JButton();
        btinventario = new javax.swing.JButton();
        btcat = new javax.swing.JButton();
        btnpro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        regresarp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 227, 201));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(180, 207, 176));
        jPanel2.setForeground(new java.awt.Color(204, 255, 204));

        btcliente.setText("CLIENTE");
        btcliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclienteActionPerformed(evt);
            }
        });

        btinventario.setText("INVENTARIO");
        btinventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinventarioActionPerformed(evt);
            }
        });

        btcat.setText("CATEGORIAS");
        btcat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcatActionPerformed(evt);
            }
        });

        btnpro.setText("PROVEEDOR");
        btnpro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnpro)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btcliente)
                        .addGap(18, 18, 18)
                        .addComponent(btinventario)))
                .addGap(18, 18, 18)
                .addComponent(btcat)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcliente)
                    .addComponent(btinventario)
                    .addComponent(btcat))
                .addGap(18, 18, 18)
                .addComponent(btnpro)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 360, -1));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("GESTION DE DATOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        regresarp.setText("REGRESAR");
        regresarp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarpActionPerformed(evt);
            }
        });
        jPanel1.add(regresarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinventarioActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btinventario)
        {
            btinventario.setEnabled(false);
            btcliente.setEnabled(false);
            btcat.setEnabled(false);
            regresarp.setEnabled(false);  
            btnpro.setEnabled(false); 
            
            inv.setVisible(true);            
            
            inv.addWindowListener(new WindowAdapter(){
               @Override
               public void windowClosing(WindowEvent we){
                    btinventario.setEnabled(true);
                    btcliente.setEnabled(true);
                    btcat.setEnabled(true);
                    regresarp.setEnabled(true);
                    btnpro.setEnabled(true); 
               }               
               public void windowClosed(WindowEvent we)
               {
                    btinventario.setEnabled(true);
                    btcliente.setEnabled(true);
                    btcat.setEnabled(true);
                    regresarp.setEnabled(true);
                    btnpro.setEnabled(true); 
               }
           });
        }
        
        
        
    }//GEN-LAST:event_btinventarioActionPerformed

    private void regresarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarpActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_regresarpActionPerformed

    private void btclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclienteActionPerformed
        // TODO add your handling code here:
         if(evt.getSource() ==btcliente)
        {
            btinventario.setEnabled(false);
            btcliente.setEnabled(false);
            btcat.setEnabled(false);
            regresarp.setEnabled(false); 
            btnpro.setEnabled(false); 
            
            vc.setVisible(true);            
            
            vc.addWindowListener(new WindowAdapter(){
               @Override
               public void windowClosing(WindowEvent we){
                    btinventario.setEnabled(true);
                    btcliente.setEnabled(true);
                    btcat.setEnabled(true);
                    regresarp.setEnabled(true);
                    btnpro.setEnabled(true); 
               }               
               public void windowClosed(WindowEvent we)
               {
                    btinventario.setEnabled(true);
                    btcliente.setEnabled(true);
                    btcat.setEnabled(true);
                    regresarp.setEnabled(true);
                    btnpro.setEnabled(true); 
               }
           });
        }
    }//GEN-LAST:event_btclienteActionPerformed

    private void btcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcatActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() ==btcat)
        {
            btinventario.setEnabled(false);
            btcliente.setEnabled(false);
            btcat.setEnabled(false);
            regresarp.setEnabled(false);        
            btnpro.setEnabled(false); 
            
            vsc.setVisible(true);            
            
            vsc.addWindowListener(new WindowAdapter(){
               @Override
               public void windowClosing(WindowEvent we){
                    btinventario.setEnabled(true);
                    btcliente.setEnabled(true);
                    btcat.setEnabled(true);
                    regresarp.setEnabled(true);
                    btnpro.setEnabled(true); 
               }               
               public void windowClosed(WindowEvent we)
               {
                    btinventario.setEnabled(true);
                    btcliente.setEnabled(true);
                    btcat.setEnabled(true);
                    regresarp.setEnabled(true);
                    btnpro.setEnabled(true); 
               }
           });
        }
    }//GEN-LAST:event_btcatActionPerformed

    private void btnproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproActionPerformed
        // TODO add your handling code here:
         if(evt.getSource() ==btnpro)
        {
            btinventario.setEnabled(false);
            btcliente.setEnabled(false);
            btcat.setEnabled(false);
            regresarp.setEnabled(false);
            btnpro.setEnabled(false);                
            
            pr.setVisible(true);            
            
            pr.addWindowListener(new WindowAdapter(){
               @Override
               public void windowClosing(WindowEvent we){
                    btinventario.setEnabled(true);
                    btcliente.setEnabled(true);
                    btcat.setEnabled(true);
                    regresarp.setEnabled(true);
                    btnpro.setEnabled(true); 
               }               
               public void windowClosed(WindowEvent we)
               {
                    btinventario.setEnabled(true);
                    btcliente.setEnabled(true);
                    btcat.setEnabled(true);
                    regresarp.setEnabled(true);
                    btnpro.setEnabled(true); 
               }
           });
        }
    }//GEN-LAST:event_btnproActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcat;
    private javax.swing.JButton btcliente;
    private javax.swing.JButton btinventario;
    private javax.swing.JButton btnpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton regresarp;
    // End of variables declaration//GEN-END:variables
}
