/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Emili
 */

import Acciones.Buscar;
import Acciones.Guardar_venta;
import Connection.Conecction;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;

import vistas.Ver_Ventas;
import vistas.Agregar_Articulos;
import vistas.Devolucion_producto;
import vistas.ticket;

public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Venta_detalle
     */
    
    Buscar busq;
    Connection c;
    Guardar_venta guardar;

    Ver_Ventas verv = new Ver_Ventas();
    Agregar_Articulos agre = new Agregar_Articulos();
    Devolucion_producto devol = new Devolucion_producto();
    ticket tick = new ticket();
    
    Guardar_venta g = new Guardar_venta();
    
    public Venta(){
        initComponents();  
        c = new Conecction().conectar();
        busq = new Buscar(c);
        this.setResizable(false); 
        this.setLocationRelativeTo(this);
        limpiar_articulos();
    }   
    
    public void limpiar_articulos(){
        combotel.removeAllItems();
        combotel.addItem("Seleccione");
        String []barras = busq.ID_cliente();
        
        for(String i:barras){
            combotel.addItem(i);
        }
        fechaventa.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        combotel = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        fechaventa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cancelarventa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        guardarventa = new javax.swing.JButton();
        actualizar1 = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        ticket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 227, 201));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("VENTAS");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("CLIENTE");

        jButton4.setText("AGREGAR ARTICULOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        combotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        combotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("FECHA");

        jPanel2.setBackground(new java.awt.Color(180, 207, 176));
        jPanel2.setForeground(new java.awt.Color(204, 255, 204));

        cancelarventa.setText("CANCELAR");
        cancelarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarventaActionPerformed(evt);
            }
        });

        jButton1.setText("REGRESAR");

        guardarventa.setText("GUARDAR");
        guardarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarventaActionPerformed(evt);
            }
        });

        actualizar1.setText("VER VENTAS");
        actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(guardarventa)
                    .addComponent(actualizar1)
                    .addComponent(cancelarventa))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(guardarventa)
                .addGap(18, 18, 18)
                .addComponent(actualizar1)
                .addGap(18, 18, 18)
                .addComponent(cancelarventa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        MODIFICAR.setText("DEVOLUCION");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        ticket.setText("TICKET");
        ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MODIFICAR)
                                .addGap(48, 48, 48)
                                .addComponent(ticket))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combotel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fechaventa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jButton4)))
                                .addGap(0, 57, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(combotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fechaventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MODIFICAR)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ticket)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jButton4)
        {
            guardarventa.setEnabled(false);
            actualizar1.setEnabled(false);
            cancelarventa.setEnabled(false);
            jButton1.setEnabled(false);
            jButton4.setEnabled(false);
            MODIFICAR.setEnabled(false);
            ticket.setEnabled(false);            
            combotel.setEnabled(false);
            fechaventa.setEnabled(false);
            
            agre.setVisible(true);            
            
            agre.addWindowListener(new WindowAdapter(){
               @Override
               public void windowClosing(WindowEvent we){
                    guardarventa.setEnabled(true);
                    actualizar1.setEnabled(true);
                    cancelarventa.setEnabled(true);
                    jButton1.setEnabled(true);
                    jButton4.setEnabled(true);
                    MODIFICAR.setEnabled(true);
                    ticket.setEnabled(true);
                    combotel.setEnabled(true);
                    fechaventa.setEnabled(true);
               }
           });
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar1ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == actualizar1)
        {
            guardarventa.setEnabled(false);
            actualizar1.setEnabled(false);
            cancelarventa.setEnabled(false);
            jButton1.setEnabled(false);
            jButton4.setEnabled(false);
            MODIFICAR.setEnabled(false);
            ticket.setEnabled(false);            
            combotel.setEnabled(false);
            fechaventa.setEnabled(false);
            
            verv.setVisible(true);            
            
            verv.addWindowListener(new WindowAdapter(){
               @Override
               public void windowClosing(WindowEvent we){
                    guardarventa.setEnabled(true);
                    actualizar1.setEnabled(true);
                    cancelarventa.setEnabled(true);
                    jButton1.setEnabled(true);
                    jButton4.setEnabled(true);
                    MODIFICAR.setEnabled(true);
                    ticket.setEnabled(true);
                    combotel.setEnabled(true);
                    fechaventa.setEnabled(true);
               }
           });
        }
    }//GEN-LAST:event_actualizar1ActionPerformed

    private void combotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotelActionPerformed
        //Obtener datos de la base de datos
        try{                       
            String idcliente = combotel.getSelectedItem().toString();
        if(!idcliente.equals("Seleccione")){             
        }
        }catch(Exception x){
            
        }
    }//GEN-LAST:event_combotelActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == MODIFICAR)
        {
            guardarventa.setEnabled(false);
            actualizar1.setEnabled(false);
            cancelarventa.setEnabled(false);
            jButton1.setEnabled(false);
            jButton4.setEnabled(false);
            MODIFICAR.setEnabled(false);
            ticket.setEnabled(false);            
            combotel.setEnabled(false);
            fechaventa.setEnabled(false);
            
            devol.setVisible(true);            
            
            devol.addWindowListener(new WindowAdapter(){
               @Override
               public void windowClosing(WindowEvent we){
                    guardarventa.setEnabled(true);
                    actualizar1.setEnabled(true);
                    cancelarventa.setEnabled(true);
                    jButton1.setEnabled(true);
                    jButton4.setEnabled(true);
                    MODIFICAR.setEnabled(true);
                    ticket.setEnabled(true);
                    combotel.setEnabled(true);
                    fechaventa.setEnabled(true);
               }
           });
        }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void cancelarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarventaActionPerformed
        limpiar_articulos();
    }//GEN-LAST:event_cancelarventaActionPerformed

    private void guardarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarventaActionPerformed
        // TODO add your handling code here:
        String fecha = fechaventa.getText();       
        if (!fecha.equals("")){
            // Convertir los datos a entero para poder insertarlos
            int montof = 0;
            //Extraer del combo el id del cliente
            int idCombo = Integer.parseInt((String)combotel.getSelectedItem());          
            g.guardarventa(idCombo, fecha, montof);
            JOptionPane.showMessageDialog(rootPane, "Venta ingresada");                   
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ingrese una fecha");
        }    
    }//GEN-LAST:event_guardarventaActionPerformed

    private void ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == ticket)
        {
            guardarventa.setEnabled(false);
            actualizar1.setEnabled(false);
            cancelarventa.setEnabled(false);
            jButton1.setEnabled(false);
            jButton4.setEnabled(false);
            MODIFICAR.setEnabled(false);
            ticket.setEnabled(false);            
            combotel.setEnabled(false);
            fechaventa.setEnabled(false);
            
            tick.setVisible(true);            
            
            tick.addWindowListener(new WindowAdapter(){
               @Override
                public void windowClosing(WindowEvent we){
                    guardarventa.setEnabled(true);
                    actualizar1.setEnabled(true);
                    cancelarventa.setEnabled(true);
                    jButton1.setEnabled(true);
                    jButton4.setEnabled(true);
                    MODIFICAR.setEnabled(true);
                    ticket.setEnabled(true);
                    combotel.setEnabled(true);
                    fechaventa.setEnabled(true);
                }
           });
        }        
    }//GEN-LAST:event_ticketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton actualizar1;
    private javax.swing.JButton cancelarventa;
    private javax.swing.JComboBox<String> combotel;
    private javax.swing.JTextField fechaventa;
    private javax.swing.JButton guardarventa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ticket;
    // End of variables declaration//GEN-END:variables
}
